TASK_STATUS_WAITING = "WAITING"
TASK_STATUS_WAITING_DISPATCH = "WAITING_DISPATCH"
TASK_STATUS_READY = "READY"
TASK_STATUS_ASSIGNED = "ASSIGNED"
TASK_STATUS_RUNNING = "RUNNING"
TASK_STATUS_COMPLETED = "COMPLETED"
TASK_STATUS_FAILED = "FAILED"
TASK_STATUS_CANCELLED = "CANCELLED"
TASK_STATUS_CANCEL_REQUESTED = "CANCEL_REQUESTED"

PHASE_FOLLOW_PATROL_PATH = "FOLLOW_PATROL_PATH"
PHASE_WAIT_FALL_RESPONSE = "WAIT_FALL_RESPONSE"

PATROL_STATUS_MOVING = "MOVING"
PATROL_STATUS_WAITING_FALL_RESPONSE = "WAITING_FALL_RESPONSE"

WAIT_FALL_RESPONSE_PHASES = frozenset(
    {
        PHASE_WAIT_FALL_RESPONSE,
        PATROL_STATUS_WAITING_FALL_RESPONSE,
    }
)


def is_waiting_fall_response(*, phase=None, patrol_status=None) -> bool:
    normalized_phase = _normalize_state(phase)
    normalized_patrol_status = _normalize_state(patrol_status)
    return (
        normalized_phase in WAIT_FALL_RESPONSE_PHASES
        or normalized_patrol_status in WAIT_FALL_RESPONSE_PHASES
    )


def _normalize_state(value):
    return str(value or "").strip().upper()


__all__ = [
    "PATROL_STATUS_MOVING",
    "PATROL_STATUS_WAITING_FALL_RESPONSE",
    "PHASE_FOLLOW_PATROL_PATH",
    "PHASE_WAIT_FALL_RESPONSE",
    "TASK_STATUS_ASSIGNED",
    "TASK_STATUS_CANCEL_REQUESTED",
    "TASK_STATUS_CANCELLED",
    "TASK_STATUS_COMPLETED",
    "TASK_STATUS_FAILED",
    "TASK_STATUS_READY",
    "TASK_STATUS_RUNNING",
    "TASK_STATUS_WAITING",
    "TASK_STATUS_WAITING_DISPATCH",
    "WAIT_FALL_RESPONSE_PHASES",
    "is_waiting_fall_response",
]
