pinky_amr_node:
  ros__parameters:
    robot_id: "pinky2"
    action_name: "/ropi/control/pinky2/navigate_to_goal"
    status_topic: "/transport/amr_status"
    current_goal_topic: "/transport/current_goal"
    state_publish_period_sec: 0.5
