robots:
  - namespace: pinky_1
    robot_name: pinky_1
    x: -7.4
    y: 4.8
    z: 0.1
    yaw: 0.0
    cam_tilt_deg: 0

  - namespace: pinky_2
    robot_name: pinky_2
    x: -6.1
    y: 4.8
    z: 0.1
    yaw: 0.0
    cam_tilt_deg: 0
