fallen_detection_client:
  ros__parameters:
    alarm_topic: "/fall_alarm"
    pinky_id: "pinky3"
    patrol_action_name: ""
    fall_response_service_name: ""
    nav_check_interval_sec: 0.2
    path_interpolation_step_m: 0.1
    segment_retry_count: 3
    segment_retry_delay_sec: 0.5
    waypoints:
      - "0.930820107460022,0.18498148024082184,0.0" # 1
      - "0.943583,-0.089052,0.0" # 2
      - "-0.039661,-0.061991,0.0" # 3
      - "-0.028806,0.297207,0.0" # 4
      - "-0.039661,-0.061991,0.0" # 5, same as 3
      - "0.715186,-0.089234,0.0" # 6
      - "0.721089,-0.506891,0.0" # 7
      - "0.255932,-0.498908,0.0" # 8
      - "1.693160,-0.494979,0.0" # 9
      - "1.701162,-0.049467,0.0" # 10
      - "1.693160,-0.494979,0.0" # 11, same as 9 position / original 8
      - "0.977322,-0.484411,0.0" # 12
      - "0.946082,0.270139,0.0" # 13, same as 1

ropi_camera:
  ros__parameters:
    server_ip: "192.168.0.76"
    udp_port: 5005
    stream_name: "pinky3_cam"
    udp_packet_size: 1200
    udp_send_buffer_size: 4194304
    session_id: 0
    send_fps: 10.0
    camera_width: 480
    camera_height: 320
    jpeg_quality: 70

patrol_path_action_server:
  ros__parameters:
    robot_id: "pinky3"
    action_name: "/ropi/control/pinky3/execute_patrol_path"
    fall_response_service_name: "/ropi/control/pinky3/fall_response_control"
    alarm_topic: "/fall_alarm"
    active_task_topic: "/ropi/robots/pinky3/active_task_id"
    nav_check_interval_sec: 0.2
    auto_start_patrol: false
